---
title: "Exercise 11"
author: "Bardia Nikpour"
output: pdf_document
date: "2024-04-09"
---

```{r setup, include=FALSE}
install.packages("tidyverse")

```

```{r}
library(tidyverse)

```

```{r}
scores <- tibble(
    name = c("mike", "carol", "greg", "marcia", "peter", "jan", "bobby", "cindy", "alice"),
    school = c("south", "south", "south", "south", "north", "north", "north", "south", "south"),
    teacher = c("johnson", "johnson", "johnson", "johnson",  "smith", "smith", "smith", "perry", "perry"),
    sex = c("male", "female", "male", "female", "male", "female", "male", "female", "female"),
    math_score = c(4, 3, 2, 4, 3, 4, 5, 4, 5),
    reading_score = c(1, 5, 2, 4, 5, 4, 1, 5, 4)
)
```



## EX 11.5
```{r}
scores %>%
  arrange(desc(math_score))

```

## Ex 11.6
```{r}
scores %>%
  arrange(name)

```

## Ex 11.7
```{r}
scores %>%
  arrange(sex)

```

## Ex 11.8
```{r}
scores %>%
  arrange()

```

## Ex 11.9
```{r}
scores %>%
  select(name, math_score, readina_score)

```

## Ex 11.10
```{r}
scores %>%
  select(-sex)

```

## Ex 11.11
```{r}
scores %>%
  select(-math_score, -reading_score)

```

## Ex 11.12
```{r}
scores %>%
  select(sex, everything())

```

## Ex 11.13
```{r}
scores %>%
  filter(sex =="male", school == "south")

```

## Ex 11.14
```{r}
scores %>%
  filter(math_score > mean(math_score))

```

## Ex 11.19
```{r}
scores %>%
  group_by(teacher) %>%
  filter(max(math_score) == 5)

```
## Ex 11.21
```{r}
scores %>%
  mutate (
math_scofe = math_score * 10,
reading_score = reading_score * 10
)

```
## Ex 11.26
```{r}
scores %>%
  group_by(sex) %>%
  mutate(math_score_centered_bysex = math_score - mean(math_score)) %>%
  arrange(desc(math_score_centered_bysex))
```